artifact_uri: file:///home/mle-user/mle-projects/mle-mlflow/mlflow_experiments_store/0/b4df87cbfe304d8f8b515b91cfc6478a/artifacts
end_time: 1756353075325
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b4df87cbfe304d8f8b515b91cfc6478a
run_name: Default
run_uuid: b4df87cbfe304d8f8b515b91cfc6478a
source_name: ''
source_type: 4
source_version: ''
start_time: 1756353075318
status: 3
tags: []
user_id: mle-user
